using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{

    ///<summary>Contains no fields, its initialization data will be lost if it is generated with RecordTemplate as parent class</summary>
  public class EmptyRecord
  {

    public EmptyRecord(Dictionary<string, object> data)
    {
      object value;
      bool status;
    }

    public EmptyRecord(Builder builder)
    {
    }
  }

  public class Builder
  {

    public EmptyRecord Build()
    {
      return new EmptyRecord(this);
    }
  }
}