// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{
  
  public enum EnumInMapRecord {
    
    Alice,
    
    Bob,
    
    ///<summary>This is the Carol doc!</summary>
    Carol,

    @UNKNOWN
  }
}