// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{
  /// <summary>This num is inline in SimpleNestedArray!</summary>
  public class EnumInSimpleNestedArray {
    public enum Value
    {

      /// <summary>Doc for X</summary>
      X,

      /// <summary>Doc for Y</summary>
      Y,

      Z,

      @UNKNOWN
    }

    public Value? value { get; }

    public EnumInSimpleNestedArray(string data)
    {
      if (data.Equals("X"))
      {
        value = Value.X;
      }
      if (data.Equals("Y"))
      {
        value = Value.Y;
      }
      if (data.Equals("Z"))
      {
        value = Value.Z;
      }
    }
  }
}