// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{
  
  public enum EnumInRecord {
    
    A,
    
    /// <summary>Doc for the B field in the inline enum!</summary>
    B,
    
    C,

    @UNKNOWN
  }
}