// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp IN THE NEW TEMPLATE AGAIN


public enum EnumInRecord {
  
  A,
  
  ///<summary>Doc for the B field in the inline enum!</summary>
  B,
  
  C,

  $UNKNOWN;
}