using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{

    ///<summary>Testing inline records for C#</summary>
  public class InlineRecord
  {

    // required
    public RecordInRecord RecordInlineField { get; }


    public InlineRecord(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for RecordInlineField
      status = data.TryGetValue("RecordInlineField", out value);
      if (status)
      {
        RecordInlineField = (RecordInRecord)value;

      }

    }

    public InlineRecord(Builder builder)
    {
      // Retrieve data for RecordInlineField
      if (builder.RecordInlineField != null)
      {
        RecordInlineField = (RecordInRecord)builder.RecordInlineField;

      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: RecordInlineField");
      }
    }
  }

  public class Builder
  {
    public RecordInRecord RecordInlineField { get; set; }

    public InlineRecord Build()
    {
      return new InlineRecord(this);
    }
  }
}