using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace PrimitiveOptionalRecord
{

    ///<summary>
///Contains fields of all supported primitive schema types
///Every field is optional
///</summary>
  public class PrimitiveOptionalRecord
  {
    ///<summary>I will make the doc look casual</summary>
    public bool? BooleanField { get; }
    public bool HasBooleanField { get; }
    ///<summary>so that you know it is not codegen-ed</summary>
    public int? IntField { get; }
    public bool HasIntField { get; }
    
    public long? LongField { get; }

    ///<summary>intentionally not leave a doc for the previous field</summary>
    public float? FloatField { get; }
    public bool HasFloatField { get; }
    
    public double? DoubleField { get; }
    public bool HasDoubleField { get; }
    
    public string StringField { get; }


    public PrimitiveOptionalRecord(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for booleanField
      status = data.TryGetValue("booleanField", out value);
      if (status)
      {
        HasBooleanField = true;
        BooleanField = (bool?)value;
      }
      else
      {
        BooleanField = (bool?)false;
        HasBooleanField = false;
      }
      // Retrieve data for intField
      status = data.TryGetValue("intField", out value);
      if (status)
      {
        HasIntField = true;
        IntField = (int?)value;
      }
      else
      {
        IntField = (int?)123;
        HasIntField = false;
      }
      // Retrieve data for longField
      status = data.TryGetValue("longField", out value);
      if (status)
      {

        LongField = (long?)value;
      }

      // Retrieve data for floatField
      status = data.TryGetValue("floatField", out value);
      if (status)
      {
        HasFloatField = true;
        FloatField = (float?)value;
      }
      else
      {
        FloatField = (float?)23.4;
        HasFloatField = false;
      }
      // Retrieve data for doubleField
      status = data.TryGetValue("doubleField", out value);
      if (status)
      {
        HasDoubleField = true;
        DoubleField = (double?)value;
      }
      else
      {
        DoubleField = (double?)3.14159;
        HasDoubleField = false;
      }
      // Retrieve data for stringField
      status = data.TryGetValue("stringField", out value);
      if (status)
      {

        StringField = (string)value;
      }

    }

    public PrimitiveOptionalRecord(Builder builder)
    {
      // Retrieve data for booleanField
      if (builder.BooleanField != null)
      {
        HasBooleanField = true;
        BooleanField = (bool?)builder.BooleanField;
      }
      else
      {
        BooleanField = (bool?)false;
        HasBooleanField = false;
      }
      // Retrieve data for intField
      if (builder.IntField != null)
      {
        HasIntField = true;
        IntField = (int?)builder.IntField;
      }
      else
      {
        IntField = (int?)123;
        HasIntField = false;
      }
      // Retrieve data for longField
      if (builder.LongField != null)
      {

        LongField = (long?)builder.LongField;
      }

      // Retrieve data for floatField
      if (builder.FloatField != null)
      {
        HasFloatField = true;
        FloatField = (float?)builder.FloatField;
      }
      else
      {
        FloatField = (float?)23.4;
        HasFloatField = false;
      }
      // Retrieve data for doubleField
      if (builder.DoubleField != null)
      {
        HasDoubleField = true;
        DoubleField = (double?)builder.DoubleField;
      }
      else
      {
        DoubleField = (double?)3.14159;
        HasDoubleField = false;
      }
      // Retrieve data for stringField
      if (builder.StringField != null)
      {

        StringField = (string)builder.StringField;
      }

    }
  }

  public class Builder
  {
    public bool? BooleanField { get; set; }
    public int? IntField { get; set; }
    public long? LongField { get; set; }
    public float? FloatField { get; set; }
    public double? DoubleField { get; set; }
    public string StringField { get; set; }

    public PrimitiveOptionalRecord build()
    {
      return new PrimitiveOptionalRecord(this);
    }
  }
}