using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{
  
  public class RecordInUnion
  {

    // required
    public int IntField { get; }


    public RecordInUnion(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for IntField
      status = data.TryGetValue("IntField", out value);
      if (status)
      {
        IntField = (int)value;

      }

    }

    public RecordInUnion(RecordInUnionBuilder builder)
    {
      // Retrieve data for IntField
      if (builder.IntField != null)
      {
        IntField = (int)builder.IntField;

      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: IntField");
      }
    }

  }

  public class RecordInUnionBuilder
  {
    public int? IntField { get; set; }

    public RecordInUnion Build()
    {
      return new RecordInUnion(this);
    }
  }
}