using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{

    
  public class RecordInRecord
  {

    // required
    public int A { get; }


    public RecordInRecord(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for A
      status = data.TryGetValue("A", out value);
      if (status)
      {
        A = (int)value;

      }

    }

    public RecordInRecord(Builder builder)
    {
      // Retrieve data for A
      if (builder.A != null)
      {
        A = (int)builder.A;

      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: A");
      }
    }
  }

  public class Builder
  {
    public int? A { get; set; }

    public RecordInRecord Build()
    {
      return new RecordInRecord(this);
    }
  }
}