using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{

    
  public class SimpleRecordProjection
  {

    // required
    public string StringField { get; }


    // required, has default value
    public int IntValue { get; }
    public bool HasIntValue { get; }

    public SimpleRecordProjection(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for StringField
      status = data.TryGetValue("StringField", out value);
      if (status)
      {
        StringField = (string)value;

      }

      // Retrieve data for IntValue
      status = data.TryGetValue("IntValue", out value);
      if (status)
      {
        IntValue = (int)value;
        HasIntValue = true;
      }
      else
      {
        IntValue = 1;
        HasIntValue = false;
      }
    }

    public SimpleRecordProjection(Builder builder)
    {
      // Retrieve data for StringField
      if (builder.StringField != null)
      {
        StringField = (string)builder.StringField;

      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: StringField");
      }
      // Retrieve data for IntValue
      if (builder.IntValue != null)
      {
        IntValue = (int)builder.IntValue;
        HasIntValue = true;
      }
      else
      {
        IntValue = 1;
        HasIntValue = false;
      }
    }
  }

  public class Builder
  {
    public string StringField { get; set; }
    public int? IntValue { get; set; }

    public SimpleRecordProjection Build()
    {
      return new SimpleRecordProjection(this);
    }
  }
}