using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace SimpleRecord
{

    
  public class SimpleRecord
  {

    // required
    public string StringField { get; }


    // required, has default value
    public int IntValue { get; }
    public bool HasIntValue { get; }

    // required, has default value
    public int AnotherIntValue { get; }
    public bool HasAnotherIntValue { get; }

    public SimpleRecord(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for StringField
      status = data.TryGetValue("StringField", out value);
      if (status)
      {

        StringField = (string)value;
      }

      // Retrieve data for IntValue
      status = data.TryGetValue("IntValue", out value);
      if (status)
      {
        HasIntValue = true;
        IntValue = (int)value;
      }
      else
      {
        IntValue = 1;
        HasIntValue = false;
      }
      // Retrieve data for AnotherIntValue
      status = data.TryGetValue("AnotherIntValue", out value);
      if (status)
      {
        HasAnotherIntValue = true;
        AnotherIntValue = (int)value;
      }
      else
      {
        AnotherIntValue = 2;
        HasAnotherIntValue = false;
      }
    }

    public SimpleRecord(Builder builder)
    {
      // Retrieve data for StringField
      if (builder.StringField != null)
      {

        StringField = (string)builder.StringField;
      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: StringField");
      }
      // Retrieve data for IntValue
      if (builder.IntValue != null)
      {
        HasIntValue = true;
        IntValue = (int)builder.IntValue;
      }
      else
      {
        IntValue = 1;
        HasIntValue = false;
      }
      // Retrieve data for AnotherIntValue
      if (builder.AnotherIntValue != null)
      {
        HasAnotherIntValue = true;
        AnotherIntValue = (int)builder.AnotherIntValue;
      }
      else
      {
        AnotherIntValue = 2;
        HasAnotherIntValue = false;
      }
    }
  }

  public class Builder
  {
    public string StringField { get; set; }
    public int? IntValue { get; set; }
    public int? AnotherIntValue { get; set; }

    public SimpleRecord build()
    {
      return new SimpleRecord(this);
    }
  }
}