using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{
  /// <summary>
  /// Simple testing for a union inside of a record.
  /// Second line of comment just because.
  /// </summary>
  public class SimpleUnion
  {

    // required
    public PrimitiveUnion primitiveUnion { get; }


    public SimpleUnion(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for primitiveUnion
      status = data.TryGetValue("primitiveUnion", out value);
      if (status)
      {
        primitiveUnion = (PrimitiveUnion)value;

      }

    }

    public SimpleUnion(SimpleUnionBuilder builder)
    {
      // Retrieve data for primitiveUnion
      if (builder.primitiveUnion != null)
      {
        primitiveUnion = (PrimitiveUnion)builder.primitiveUnion;

      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: primitiveUnion");
      }
    }

    public class PrimitiveUnion
    {
      public string asString { get; }
      public int? asInt { get; }
      public Mode? dataMode { get; }
    
      public enum Mode
      {
        String,
        Int,
        NULL
      }
    
      public PrimitiveUnion(string value)
      {
        asString = value;
        dataMode = Mode.String;
      }
    
      public PrimitiveUnion(int value)
      {
        asInt = value;
        dataMode = Mode.Int;
      }
    }
    
    public class PrimitiveUnionBuilder
    {
    
    }
  }

  public class SimpleUnionBuilder
  {
    public PrimitiveUnion primitiveUnion { get; set; }

    public SimpleUnion Build()
    {
      return new SimpleUnion(this);
    }
  }
}