using System.Collections.Generic;
using System;


// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp

namespace com.linkedin.restli.datagenerator.integration
{

    ///<summary>Test simple nested array</summary>
  public class SimpleNestedArray
  {

    // required
    public IReadOnlyList<IReadOnlyList<int>> IntArray { get; }


    public SimpleNestedArray(Dictionary<string, object> data)
    {
      object value;
      bool status;
      // Retrieve data for IntArray
      status = data.TryGetValue("IntArray", out value);
      if (status)
      {

        IntArray = (IReadOnlyList<IReadOnlyList<int>>)value;
      }

    }

    public SimpleNestedArray(Builder builder)
    {
      // Retrieve data for IntArray
      if (builder.IntArray != null)
      {

        IntArray = (IReadOnlyList<IReadOnlyList<int>>)builder.IntArray;
      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: IntArray");
      }
    }
  }

  public class Builder
  {
    public IReadOnlyList<IReadOnlyList<int>> IntArray { get; set; }

    public SimpleNestedArray Build()
    {
      return new SimpleNestedArray(this);
    }
  }
}