// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp IN THE NEW TEMPLATE AGAIN

///<summary>Doc for the enum</summary>
public enum TestEnum {
  
  ///<summary>Doc for 1</summary>
  SYMBOL_1,
  
  SYMBOL_2,
  
  ///<summary>Doc for 3</summary>
  SYMBOL_3,

  $UNKNOWN;
}