// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com/linkedin/restli/datagenerator/integration/MapTest.pdsc

namespace com.linkedin.restli.datagenerator.integration
{
  
  public class EnumInMapTest {
    public enum Value
    {

      A,

      B,

      @UNKNOWN
    }

    public Value? value { get; }

    public EnumInMapTest(string data)
    {
      if (data.Equals("A"))
      {
        value = Value.A;
      }
      else if (data.Equals("B"))
      {
        value = Value.B;
      }
      else
      {
        throw new System.ArgumentNullException("Argument in enum constructor invalid for enum: EnumInMapTest");
      }
    }
  }
}