using System.Collections.Generic;
using System;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com/linkedin/restli/datagenerator/integration/MapTest.pdsc

namespace com.linkedin.restli.datagenerator.integration
{
  
  public class RecordInMapTest
  {

    // required
    public int f { get; }


    public RecordInMapTest(Dictionary<string, object> data)
    {
      object value;
      // Retrieve data for f
      if (data.TryGetValue("f", out value))
      {
        f = (int)value;

      }

    }

    public RecordInMapTest(RecordInMapTestBuilder builder)
    {
      // Retrieve data for f
      if (builder.f != null)
      {
        f = (int)builder.f;

      }
      else
      {
        throw new System.ArgumentNullException("Required field with no default must be included in builder: f");
      }
    }

  }

  public class RecordInMapTestBuilder
  {
    public int? f { get; set; }

    public RecordInMapTest Build()
    {
      return new RecordInMapTest(this);
    }
  }
}