using restlicsharpdata.restlidata;
using System;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com/linkedin/restli/datagenerator/integration/UnionTest.pdsc

namespace com.linkedin.restli.datagenerator.integration
{
  
  public class EnumInUnionTest : EnumTemplate
  {
    public enum Symbol
    {

      A,

      B,

      C,

      UNKNOWN
    }

    public Symbol symbol { get; }

    public EnumInUnionTest(Symbol symbol)
    {
      this.symbol = symbol;
    }

    public EnumInUnionTest(string data)
    {
      if (data.Equals("A"))
      {
        symbol = Symbol.A;
      }
      else if (data.Equals("B"))
      {
        symbol = Symbol.B;
      }
      else if (data.Equals("C"))
      {
        symbol = Symbol.C;
      }
      else
      {
        symbol = Symbol.UNKNOWN;
      }
    }
  }
}