using System;
using System.Collections.Generic;
using System.Linq;

using restlicsharpdata.restlidata;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com\linkedin\restli\common\EmptyRecord.pdsc

namespace com.linkedin.restli.common
{
  /// <summary>
/// An literally empty record.  Intended as a marker to indicate the absence of content where a record type is required.  If used the underlying DataMap *must* be empty, EmptyRecordValidator is provided to help enforce this.  For example,  CreateRequest extends Request<EmptyRecord> to indicate it has no response body.   Also, a ComplexKeyResource implementation that has no ParamKey should have a signature like XyzResource implements ComplexKeyResource<XyzKey, EmptyRecord, Xyz>.
/// </summary>
  public class EmptyRecord : RecordTemplate
  {

    public EmptyRecord(Dictionary<string, object> data)
    {
      object value;
    }

    public EmptyRecord(EmptyRecordBuilder builder)
    {
    }

    public Dictionary<string, object> Data()
    {
      Dictionary<string, object> dataMap = new Dictionary<string, object>();
      return dataMap;
    }

  }

  public class EmptyRecordBuilder
  {

    public EmptyRecord Build()
    {
      return new EmptyRecord(this);
    }
  }
}
