using System;
using System.Collections.Generic;
using System.Linq;

using restlicsharpdata.restlidata;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com\linkedin\restli\common\UpdateStatus.pdsc

namespace com.linkedin.restli.common
{
  /// <summary>
/// A rest.li update status.
/// </summary>
  public class UpdateStatus : RecordTemplate
  {

    public int status { get; }
    public bool hasStatus { get; }

    public ErrorResponse error { get; }
    public bool hasError { get; }

    public UpdateStatus(Dictionary<string, object> data)
    {
      object value;
      // Retrieve data for status
      if (data.TryGetValue("status", out value))
      {
        
status = Convert.ToInt32(value);
        hasStatus = true;
      }
      else
      {

        hasStatus = false;
      }
      // Retrieve data for error
      if (data.TryGetValue("error", out value))
      {
        
error = new ErrorResponse((Dictionary<string, object>)value);
        hasError = true;
      }
      else
      {

        hasError = false;
      }
    }

    public UpdateStatus(UpdateStatusBuilder builder)
    {
      // Retrieve data for status
      if (builder.status != null)
      {
        
status = (int)builder.status;
        hasStatus = true;
      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: status");

      }
      // Retrieve data for error
      if (builder.error != null)
      {
        
error = builder.error;
        hasError = true;
      }
      else
      {

        hasError = false;
      }
    }

    public Dictionary<string, object> Data()
    {
      Dictionary<string, object> dataMap = new Dictionary<string, object>();
      if (hasStatus)
        dataMap.Add("status", status);
      if (hasError)
        dataMap.Add("error", error.Data());
      return dataMap;
    }

  }

  public class UpdateStatusBuilder
  {
    public int? status { get; set; }
    public ErrorResponse error { get; set; }

    public UpdateStatus Build()
    {
      return new UpdateStatus(this);
    }
  }
}
