using System.Collections.Generic;
using System;
using restlicsharpdata.restlidata;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com/linkedin/restli/datagenerator/integration/SimpleRecord.pdsc

namespace com.linkedin.restli.datagenerator.integration
{
  
  public class SimpleRecord : RecordTemplate
  {

    public string stringField { get; }


    public int intValue { get; }
    public bool hasIntValue { get; }

    public int anotherIntValue { get; }
    public bool hasAnotherIntValue { get; }

    public SimpleRecord(Dictionary<string, object> data)
    {
      object value;
      // Retrieve data for stringField
      if (data.TryGetValue("stringField", out value))
      {
        
        stringField = (string)value;

      }

      // Retrieve data for intValue
      if (data.TryGetValue("intValue", out value))
      {
        
        intValue = (int)value;
        hasIntValue = true;
      }
      else
      {
        intValue = 1;
        hasIntValue = false;
      }
      // Retrieve data for anotherIntValue
      if (data.TryGetValue("anotherIntValue", out value))
      {
        
        anotherIntValue = (int)value;
        hasAnotherIntValue = true;
      }
      else
      {
        anotherIntValue = 2;
        hasAnotherIntValue = false;
      }
    }

    public SimpleRecord(SimpleRecordBuilder builder)
    {
      // Retrieve data for stringField
      if (builder.stringField != null)
      {
        
        stringField = builder.stringField;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: stringField");
      }
      // Retrieve data for intValue
      if (builder.intValue != null)
      {
        
        intValue = (int)builder.intValue;
        hasIntValue = true;
      }
      else
      {
        intValue = 1;
        hasIntValue = false;
      }
      // Retrieve data for anotherIntValue
      if (builder.anotherIntValue != null)
      {
        
        anotherIntValue = (int)builder.anotherIntValue;
        hasAnotherIntValue = true;
      }
      else
      {
        anotherIntValue = 2;
        hasAnotherIntValue = false;
      }
    }

  }

  public class SimpleRecordBuilder
  {
    public string stringField { get; set; }
    public int? intValue { get; set; }
    public int? anotherIntValue { get; set; }

    public SimpleRecord Build()
    {
      return new SimpleRecord(this);
    }
  }
}