using restlicsharpdata.restlidata;
using System;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com/linkedin/restli/datagenerator/integration/TestEnum.pdsc

namespace com.linkedin.restli.datagenerator.integration
{
  /// <summary>Doc for the enum</summary>
  public class TestEnum : EnumTemplate
  {
    public enum Value
    {

      /// <summary>Doc for 1</summary>
      SYMBOL_1,

      SYMBOL_2,

      /// <summary>Doc for 3</summary>
      SYMBOL_3,

      @UNKNOWN
    }

    public Value? value { get; }

    public TestEnum(string data)
    {
      if (data.Equals("SYMBOL_1"))
      {
        value = Value.SYMBOL_1;
      }
      else if (data.Equals("SYMBOL_2"))
      {
        value = Value.SYMBOL_2;
      }
      else if (data.Equals("SYMBOL_3"))
      {
        value = Value.SYMBOL_3;
      }
      else
      {
        throw new ArgumentException("Argument in enum constructor invalid for enum: TestEnum");
      }
    }
  }
}