using System.Collections.Generic;
using System;
using restlicsharpdata.restlidata;

// DO NOT EDIT - THIS FILE IS GENERATED BY restli-csharp
// Generated from com/linkedin/restli/datagenerator/integration/ThoroughRecord.pdsc

namespace com.linkedin.restli.datagenerator.integration
{
  
  public class ThoroughRecord : RecordTemplate
  {

    public string stringField { get; }


    public int intValue { get; }


    public float floatField { get; }


    public double doubleField { get; }


    public long longField { get; }


    public bool booleanField { get; }


    public Bytes bytesField { get; }


    public TestEnum enumField { get; }


    public ThoroughRecord(Dictionary<string, object> data)
    {
      object value;
      // Retrieve data for stringField
      if (data.TryGetValue("stringField", out value))
      {
        
        stringField = (string)value;

      }

      // Retrieve data for intValue
      if (data.TryGetValue("intValue", out value))
      {
        
        intValue = (int)value;

      }

      // Retrieve data for floatField
      if (data.TryGetValue("floatField", out value))
      {
        
        floatField = (float)value;

      }

      // Retrieve data for doubleField
      if (data.TryGetValue("doubleField", out value))
      {
        
        doubleField = (double)value;

      }

      // Retrieve data for longField
      if (data.TryGetValue("longField", out value))
      {
        
        longField = (long)value;

      }

      // Retrieve data for booleanField
      if (data.TryGetValue("booleanField", out value))
      {
        
        booleanField = (bool)value;

      }

      // Retrieve data for bytesField
      if (data.TryGetValue("bytesField", out value))
      {
        
        bytesField = new Bytes(BytesUtil.StringToBytes((string)value));

      }

      // Retrieve data for enumField
      if (data.TryGetValue("enumField", out value))
      {
        
        enumField = new TestEnum((string)value);

      }

    }

    public ThoroughRecord(ThoroughRecordBuilder builder)
    {
      // Retrieve data for stringField
      if (builder.stringField != null)
      {
        
        stringField = (string)builder.stringField;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: stringField");
      }
      // Retrieve data for intValue
      if (builder.intValue != null)
      {
        
        intValue = (int)builder.intValue;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: intValue");
      }
      // Retrieve data for floatField
      if (builder.floatField != null)
      {
        
        floatField = (float)builder.floatField;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: floatField");
      }
      // Retrieve data for doubleField
      if (builder.doubleField != null)
      {
        
        doubleField = (double)builder.doubleField;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: doubleField");
      }
      // Retrieve data for longField
      if (builder.longField != null)
      {
        
        longField = (long)builder.longField;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: longField");
      }
      // Retrieve data for booleanField
      if (builder.booleanField != null)
      {
        
        booleanField = (bool)builder.booleanField;

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: booleanField");
      }
      // Retrieve data for bytesField
      if (builder.bytesField != null)
      {
        
        bytesField = new Bytes(BytesUtil.StringToBytes((string)builder.bytesField));

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: bytesField");
      }
      // Retrieve data for enumField
      if (builder.enumField != null)
      {
        
        enumField = new TestEnum((string)builder.enumField);

      }
      else
      {
        throw new ArgumentException("Required field with no default must be included in builder: enumField");
      }
    }

  }

  public class ThoroughRecordBuilder
  {
    public string stringField { get; set; }
    public int? intValue { get; set; }
    public float? floatField { get; set; }
    public double? doubleField { get; set; }
    public long? longField { get; set; }
    public bool? booleanField { get; set; }
    public Bytes bytesField { get; set; }
    public TestEnum enumField { get; set; }

    public ThoroughRecord Build()
    {
      return new ThoroughRecord(this);
    }
  }
}